--filetypes data file
INSERT INTO filetypes (filetype_id, filetype_name)
VALUES
  (1, 'Condition'),
  (2, 'Death Cause'),
  (3, 'Death'),
  (4, 'Demographic'),
  (5, 'Diagnosis'),
  (6, 'Dispensing'),
  (7, 'Encounter'),
  (8, 'Enrollment'),
  (9, 'Lab_result_cm'),
  (10, 'Prescribing'),
  (11, 'Procedures'),
  (12, 'Vital'),
  (13, 'HCN_AllergyFeed'),
  (14, 'HCN_AppointmentFeed'),
  (15, 'HCN_ChargeActivityFeed'),
  (16, 'HCN_ChargeFeed'),
  (17, 'HCN_DocumentFeed'),
  (18, 'HCN_ElligibilityFeed'),
  (20, 'HCN_EncounterFeed'),
  (21, 'HCN_EncounterFindingFeed'),
  (22, 'HCN_LabFeed'),
  (23, 'HCN_LabLoincFeed'),
  (24, 'HCN_MedicationFeed'),
  (25, 'HCN_PatientFeed'),
  (26, 'HCN_ProblemFeed'),
  (27, 'HCN_ProcedureFeed'),
  (28, 'HCN_ProviderFeed'),
  (29, 'HCN_SiteFeed'),
  (30, 'HCN_StandardEncounterFeed'),
  (31, 'HCN_VitalFeed'),
  (32, 'Unknown'),
  (33, 'Tumor'),
  (34, 'Tumor_Registry_Concept') --ORH-specific
